import { Component } from '@angular/core';

import { NavController } from 'ionic-angular';
import JSZip from 'jszip';
import JSZipUtils from 'jszip-utils';
import FileSaver from 'file-saver';
import Docxtemplater from 'docxtemplater';


@Component({
  selector: 'page-content',
  templateUrl: 'content.html'
})
export class ContentPage {

  constructor(public navCtrl: NavController) { }
  loadFile(url: string, callback) {

    JSZipUtils.getBinaryContent(url, callback);
  };

  runloadfile() {
    let result = this.loadFile("../assets/examples/S-140-S-template.docx", function (error, content) {
      if (error) { throw error };
      var zip = new JSZip(content);
      var doc = new Docxtemplater().loadZip(zip)
      doc.setData({
        "cong": "Congregación Danlí Señas",
        "semanas": [
          {
            sabasamblea: false,
            sabasambleamensage: "Hay asamblea",
            fecha: "fecha1",
            presidente: "Presidente",
            cancion1: "Cancion1",
            respcancion1: "Nombre cancion 1",            
            oracion1: "Oracion1",
            tb1titulo: "Discurso1 Titulo",
            tb1orador: "Orador 1omin",
            tbperlasorador: "Oradar Perlas",
            consejolector: "1",
            tblector: "Lector Biblia",
            hayestudiantes: false,
            consejoprimera: "2",
            smmprimeraes: "smmprimeraes",
            smmprimeraayu: "smmprimeraayu",
            consejorevisita: "3",
            smmrevisitaes: "smmrevisitaes",
            smmrevisitaayu: "smmrevisitaayu",
            escurso: true,
            consejocb: "4",
            smmcbes: "smmcbes",
            smmcbayu: "smmcbayu",
            presentacionesmes: "presentacionesmes",
            cancion2: "Cancion 2",
            respcancion2: "Nombre cancion 2",            
            nvctitulo1: "Titulo 1",
            nvcmins1: "nvcmins1",
            nvcorador1: "Orador 1",
            nvctitulo2: "Titulo 2",
            nvcmins2: "nvcmins2",
            nvcorador2: "Orador 2",
            nvcestudioorador: "Estudio Libro conductor",
            nvcestudiolector: "nvcestudiolector",
            cancion3: "Cancion 3",
            respcancion3: "Nombre cancion 3",
            oracion2: "Oracion 2",
            camara: "camara",
            aparatos: "aparatos",
            cronometro: "cronometro",
            ini1h1: "0:00",
            ini2h1: "0:00",
            tb1h1: "0:00",
            tb2h1: "0:00",
            tb3h1: "0:00",
            smm1h1: "0:00",
            smm2h1: "0:00",
            smm3h1: "0:00",
            nvc1h1: "0:00",
            nvc2h1: "0:00",
            nvc3h1: "0:00",
            nvc4h1: "0:00",
            nvc5h1: "0:00",
            nvc6h1: "0:00",
            nvc6h2: "0:00",
            domasamblea: false,
            domasambleamensage: "Hay asamblea",
            domfecha: "Domingo fecha",
            dompresidente: "Presidente",
            domdiscursante: "Discursante",
            domhaydiscursante: false,
            domlectura: "Lector Atalaya"
          },
          {
            sabasamblea: false,
            sabasambleamensage: "Hay asamblea",
            fecha: "fecha2",
            presidente: "Presidente",
            cancion1: "Cancion1",
            respcancion1: "Nombre cancion 1",     
            oracion1: "Oracion1",
            tb1titulo: "Discurso1 Titulo",
            tb1orador: "Orador 1omin",
            tbperlasorador: "Oradar Perlas",
            consejolector: "1",
            tblector: "Lector Biblia",
            hayestudiantes: true,
            consejoprimera: "2",
            smmprimeraes: "smmprimeraes",
            smmprimeraayu: "smmprimeraayu",
            consejorevisita: "3",
            smmrevisitaes: "smmrevisitaes",
            smmrevisitaayu: "smmrevisitaayu",
            escurso: true,
            consejocb: "4",
            smmcbes: "smmcbes",
            smmcbayu: "smmcbayu",
            presentacionesmes: "presentacionesmes",
            cancion2: "Cancion 2",
            respcancion2: "Nombre cancion 2",     
            nvctitulo1: "Titulo 1",
            nvcmins1: "nvcmins1",
            nvcorador1: "Orador 1",
            nvctitulo2: "Titulo 2",
            nvcmins2: "nvcmins2",
            nvcorador2: null,
            nvcestudioorador: "Estudio Libro conductor",
            nvcestudiolector: "nvcestudiolector",
            cancion3: "Cancion 3",
            respcancion3: "Nombre cancion 3",     
            oracion2: "Oracion 2",
            camara: "camara",
            aparatos: "aparatos",
            cronometro: "cronometro",
            ini1h1: "0:00",
            ini2h1: "0:00",
            tb1h1: "0:00",
            tb2h1: "0:00",
            tb3h1: "0:00",
            smm1h1: "0:00",
            smm2h1: "0:00",
            smm3h1: "0:00",
            nvc1h1: "0:00",
            nvc2h1: "0:00",
            nvc3h1: "0:00",
            nvc4h1: "0:00",
            nvc5h1: "0:00",
            nvc6h1: "0:00",
            nvc6h2: "0:00",
            domasamblea: false,
            domasambleamensage: "Hay asamblea",
            domfecha: "Domingo fecha",
            dompresidente: "Presidente",
            domdiscursante: "Discursante",
            domhaydiscursante: true,
            domlectura: "Lector Atalaya"
          },
          {
            sabasamblea: false,
            sabasambleamensage: "Hay asamblea",
            fecha: "fecha3",
            presidente: "Presidente",
            cancion1: "Cancion1",
            respcancion1: "Nombre cancion 1",     
            oracion1: "Oracion1",
            tb1titulo: "Discurso1 Titulo",
            tb1orador: "Orador 1omin",
            tbperlasorador: "Oradar Perlas",
            consejolector: "1",
            tblector: "Lector Biblia",
            hayestudiantes: true,
            consejoprimera: "2",
            smmprimeraes: "smmprimeraes",
            smmprimeraayu: "smmprimeraayu",
            consejorevisita: "3",
            smmrevisitaes: "smmrevisitaes",
            smmrevisitaayu: "smmrevisitaayu",
            escurso: true,
            consejocb: "4",
            smmcbes: "smmcbes",
            smmcbayu: "smmcbayu",
            presentacionesmes: "presentacionesmes",
            cancion2: "Cancion 2",
            respcancion2: "Nombre cancion 2",     
            nvctitulo1: "Titulo 1",
            nvcmins1: "nvcmins1",
            nvcorador1: "Orador 1",
            nvctitulo2: "Titulo 2",
            nvcmins2: "nvcmins2",
            nvcorador2: "Orador 2",
            nvcestudioorador: "Estudio Libro conductor",
            nvcestudiolector: "nvcestudiolector",
            cancion3: "Cancion 3",
            respcancion3: "Nombre cancion 3",     
            oracion2: "Oracion 2",
            camara: "camara",
            aparatos: "aparatos",
            cronometro: "cronometro",
            ini1h1: "0:00",
            ini2h1: "0:00",
            tb1h1: "0:00",
            tb2h1: "0:00",
            tb3h1: "0:00",
            smm1h1: "0:00",
            smm2h1: "0:00",
            smm3h1: "0:00",
            nvc1h1: "0:00",
            nvc2h1: "0:00",
            nvc3h1: "0:00",
            nvc4h1: "0:00",
            nvc5h1: "0:00",
            nvc6h1: "0:00",
            nvc6h2: "0:00",
            domasamblea: false,
            domasambleamensage: "Hay asamblea",
            domfecha: "Domingo fecha",
            dompresidente: "Presidente",
            domdiscursante: "Discursante",
            domhaydiscursante: true,
            domlectura: "Lector Atalaya"
          },
          {
            sabasamblea: true,
            sabasambleamensage: "Hay asamblea",
            fecha: "fecha4",
            presidente: "Presidente",
            cancion1: "Cancion1",
            respcancion1: "Nombre cancion 1",     
            oracion1: "Oracion1",
            tb1titulo: "Discurso1 Titulo",
            tb1orador: "Orador 1omin",
            tbperlasorador: "Oradar Perlas",
            consejolector: "1",
            tblector: "Lector Biblia",
            hayestudiantes: true,
            consejoprimera: "2",
            smmprimeraes: "smmprimeraes",
            smmprimeraayu: "smmprimeraayu",
            consejorevisita: "3",
            smmrevisitaes: "smmrevisitaes",
            smmrevisitaayu: "smmrevisitaayu",
            escurso: true,
            consejocb: "4",
            smmcbes: "smmcbes",
            smmcbayu: "smmcbayu",
            presentacionesmes: "presentacionesmes",
            cancion2: "Cancion 2",
            respcancion2: "Nombre cancion 2",     
            nvctitulo1: "Titulo 1",
            nvcmins1: "nvcmins1",
            nvcorador1: "Orador 1",
            nvctitulo2: "Titulo 2",
            nvcmins2: "nvcmins2",
            nvcorador2: "Orador 2",
            nvcestudioorador: "Estudio Libro conductor",
            nvcestudiolector: "nvcestudiolector",
            cancion3: "Cancion 3",
            respcancion3: "Nombre cancion 3",  
            oracion2: "Oracion 2",
            camara: "camara",
            aparatos: "aparatos",
            cronometro: "cronometro",
            ini1h1: "0:00",
            ini2h1: "0:00",
            tb1h1: "0:00",
            tb2h1: "0:00",
            tb3h1: "0:00",
            smm1h1: "0:00",
            smm2h1: "0:00",
            smm3h1: "0:00",
            nvc1h1: "0:00",
            nvc2h1: "0:00",
            nvc3h1: "0:00",
            nvc4h1: "0:00",
            nvc5h1: "0:00",
            nvc6h1: "0:00",
            nvc6h2: "0:00",
            domasamblea: false,
            domasambleamensage: "Hay asamblea",
            domfecha: "Domingo fecha",
            dompresidente: "Presidente",
            domdiscursante: "Discursante",
            domhaydiscursante: true,
            domlectura: "Lector Atalaya"
          },
          {
            sabasamblea: false,
            sabasambleamensage: "Hay asamblea",
            fecha: "fecha5",
            presidente: "Presidente",
            cancion1: "Cancion1",
            respcancion1: "Nombre cancion 1",     
            oracion1: "Oracion1",
            tb1titulo: "Discurso1 Titulo",
            tb1orador: "Orador 1omin",
            tbperlasorador: "Oradar Perlas",
            consejolector: "1",
            tblector: "Lector Biblia",
            hayestudiantes: true,
            consejoprimera: "2",
            smmprimeraes: "smmprimeraes",
            smmprimeraayu: "smmprimeraayu",
            consejorevisita: "3",
            smmrevisitaes: "smmrevisitaes",
            smmrevisitaayu: "smmrevisitaayu",
            escurso: false,
            consejocb: "4",
            smmcbes: "smmcbes",
            smmcbayu: "smmcbayu",
            presentacionesmes: "presentacionesmes",
            cancion2: "Cancion 2",
            respcancion2: "Nombre cancion 2",     
            nvctitulo1: "Titulo 1",
            nvcmins1: "nvcmins1",
            nvcorador1: "Orador 1",
            nvctitulo2: "Titulo 2",
            nvcmins2: "nvcmins2",
            nvcorador2: "Orador 2",
            nvcestudioorador: "Estudio Libro conductor",
            nvcestudiolector: "nvcestudiolector",
            cancion3: "Cancion 3",
            respcancion3: "Nombre cancion 3",     
            oracion2: "Oracion 2",
            camara: "camara",
            aparatos: "aparatos",
            cronometro: "cronometro",
            ini1h1: "0:00",
            ini2h1: "0:00",
            tb1h1: "0:00",
            tb2h1: "0:00",
            tb3h1: "0:00",
            smm1h1: "0:00",
            smm2h1: "0:00",
            smm3h1: "0:00",
            nvc1h1: "0:00",
            nvc2h1: "0:00",
            nvc3h1: "0:00",
            nvc4h1: "0:00",
            nvc5h1: "0:00",
            nvc6h1: "0:00",
            nvc6h2: "0:00",
            domasamblea: false,
            domasambleamensage: "Hay asamblea",
            domfecha: "Domingo fecha",
            dompresidente: "Presidente",
            domdiscursante: "Discursante",
            domhaydiscursante: true,
            domlectura: "Lector Atalaya"
          },

        ]

      }
      );

      try {
        // render the document (replace all occurences of {first_name} by John, {last_name} by Doe, ...)
        doc.render()
      }
      catch (error) {
        var e = {
          message: error.message,
          name: error.name,
          stack: error.stack,
          properties: error.properties,
        }
        console.log(JSON.stringify({ error: e }));
        // The error thrown here contains additional information when logged with JSON.stringify (it contains a property object).
        throw error;
      }
      var out = doc.getZip().generate({
        type: "blob",
        mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      }) //Output the document using Data-URI
      FileSaver.saveAs(out, "output.docx")
    }
    )
  };
}





